### ISSUE TITLE
No Villages Spawning

### ISSUE THREAD

**Issue by Airisii** [ToMe25/ToMeSetup#4] opened 2019-12-31 03:26 UTC
When I load a world with this mod no villages are spawning.

**Comment by ToMe25** [comment] 2019-12-31 10:36
Please add some additional information like the Minecraft version you are using, the version of this mod you are using and what other mods you are using so i can try to reproduce this, as i didn't encounter this Issue in my tests.

**Comment by LegendaryCrystalFox** [comment] 2020-01-01 00:26
Minecraft Version: Forge 14.23.5.2831
Mod Version: 1.6.2
The mod I'm using is: https://www.curseforge.com/minecraft/mc-mods/village-spawn-point

**Comment by ToMe25** [comment] 2020-01-01 09:04
I can't test this rn but i think villages are generating, you just aren't spawning in a village because this mod sets the worldspawn to exactly 0, 0 after village-spawn-point sets it in a village.
Disable the worldspawn enable option to prevent this mod from setting your spawnpoint and this shouldn't happen anymore.

**Comment by ToMe25** [comment] 2020-01-01 10:05
I Tested this now and at least for me in a world with this two mods Villages do generate, i just don't spawn in one as long as setWorldSpawn is enabled.

**Comment by LegendaryCrystalFox** [comment] 2020-01-01 19:34
Ok, thank you.

**Comment by ToMe25** [comment] 2020-01-01 20:18
If there are still villages generating please close this issue :)

**Closed as completed** 2020-01-02 02:33 UTC
Labels: question, wontfix, can't reproduce
